version: '3.6'
services:
  app:
    image: flash-sale
    build: .
    ports:
      - 8081:8081
    working_dir: /app
    depends_on:
      - mongo
    links:
      - mongo
    environment:
      PORT: 8081
      HOST: https://quick-start-3ef77817.myshopify.com
      SHOPIFY_API_KEY: b45c25c2b7db4dbad7e35840e272869e
      SHOPIFY_API_SECRET: dfb0e5b3bc2699a8e8f2a7e55caae8fb
      SCOPES: write_products
      
  mongo:
    image: mongo
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_DATABASE: flash-sale
    volumes:
      - ./data:/data/db
volumes:
  data:



      
